### PR TITLE
Symfony upgraded to the `v5.2`.

### PR DESCRIPTION
**Pull request by automatix**

### CODE REVIEW

**Comment by MolloKhan** [comment]
Hey @automatix did you get a problem with this tutorial that forced you to upgrade to Symfony5.2? I'd like to know more about what made you to push this PR

**Comment by automatix** [comment]
@larzuk91 Hi Diego, not really. I'd just find it nice to keep the repo up-to-date. (And if I remember correctly, there was an issue, that the `composer.json` and `composer.lock` were not in sync. But I'm not sure.)

**Comment by MolloKhan** [comment]
Hey @automatix I appreciate your effort but I'll have to close your PR because we use an internal tool for updating the code of a tutorial. Thanks anyway!

**Comment by automatix** [comment]
@larzuk91 OK, no problem. Thank you anyway for the feedback! "Update tool" sound interesting. It would nice to see it. If possible and doesn't generate much effort for you, of course.

**Comment by bocharsky-bw** [comment]
Hey @automatix !

Unfortunately, it's our secret internal tool, it's not publicly available :)

Cheers!

**Pull request closed without merging**
